#!/bin/bash
source ${HOME}/.ec2/ec2_keys
INSTANCES="current_instances"

if [ -f $INSTANCES ]; then
    for i in `cat $INSTANCES`; do
    	VMS="$VMS $i"
	ec2-describe-instances $i | grep "INSTANCE" | awk '{ print $7"\t"$14"\t"$15 }'
    done
fi
