#!/bin/bash

export PATH=$PATH:/opt/hadoop/bin

USER=40

for ((i=0;i<=$USER;i++)); do
  USERID=$(printf "user%02d" $i)
  echo $USERID
  hadoop fs -mkdir -p      /user/$USERID
  hadoop fs -chown $USERID /user/$USERID
  hadoop fs -chmod 700     /user/$USERID
done

# fix mapreduce permission
hadoop fs -chmod a+w /opt/hadoop/var/hadoop-root/mapred
