#!/bin/bash
if [ ! -x /usr/bin/ant ]; then
  sudo apt-get -y install ant
fi

if [ ! -f ${HOME}/hadoop/hadoop-core-*.jar.org ]; then
  file=`ls ${HOME}/hadoop/hadoop-core-*.jar`
  echo "Backup $file to $file.org"
  cp $file $file.org
fi

if [ "$(pidof java)" != "" ]; then
  ${HOME}/hadoop/bin/hadoop-daemon.sh stop tasktracker
  ${HOME}/hadoop/bin/hadoop-daemon.sh stop datanode
  ${HOME}/hadoop/bin/hadoop-daemon.sh stop jobtracker
  ${HOME}/hadoop/bin/hadoop-daemon.sh stop namenode
  sleep 5
fi	

if [ -e ${HOME}/hadoop/conf ]; then
  rm ${HOME}/hadoop/conf
fi
ln -s ${HOME}/hadoop/conf.pseudo ${HOME}/hadoop/conf

if [ "$(pidof java)" == "" ]; then
  ${HOME}/hadoop/bin/hadoop-daemon.sh start namenode
  ${HOME}/hadoop/bin/hadoop-daemon.sh start datanode
  ${HOME}/hadoop/bin/hadoop-daemon.sh start jobtracker
  ${HOME}/hadoop/bin/hadoop-daemon.sh start tasktracker
fi	

bin=`dirname $0`
bin=`cd "$bin"; pwd`

cd $bin
export JAVA_HOME=/usr/lib/jvm/java-6-sun
export PATH=${HOME}/hadoop/bin:$PATH
ant

echo " *** Press Enter to continue *** "
read
clear

echo "====================================="
echo "jar tvf ${HOME}/hadoop/hadoop-core-1.0.4.jar | grep FsShell"
echo "====================================="
jar tvf ${HOME}/hadoop/hadoop-core-1.0.4.jar | grep FsShell
echo "====================================="
echo "jar tvf ${HOME}/hadoop/hadoop-core-1.0.4.jar.org | grep FsShell"
echo "====================================="
jar tvf ${HOME}/hadoop/hadoop-core-1.0.4.jar.org | grep FsShell
echo " *** Press Enter to continue ***"
read
clear

echo "====================================="
export HADOOP_CONF_DIR=~/hadoop/conf.local/
hadoop fs -ls
hadoop fs -ls /home
echo "====================================="
unset HADOOP_CONF_DIR
hadoop fs -ls 
hadoop fs -ls /home
