#!/bin/bash
if [ ! -x /usr/bin/ant ]; then
  sudo apt-get install ant
fi

if [ ! -f ${HOME}/hadoop/hadoop-core-*.jar.org ]; then
  file=`ls ${HOME}/hadoop/hadoop-core-*.jar`
  echo "Backup $file to $file.org"
  cp $file $file.org
fi
